services:
  server:
    image: lscr.io/linuxserver/your_spotify:latest
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      APP_URL: http://192.168.1.170:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CORS : http://192.168.1.170:8080
      SPOTIFY_PUBLIC: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      MONGO_ENDPOINT : mongodb://mongo:27017/your_spotify
  
  # erreur pas d'avx sur mes xeon
  # :4.4.6
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://192.168.1.170:8080


