services:
  server:
    container_name: your_spotify_server 
    image: yooooomi/your_spotify_server
    restart: always
    # ports:
    #   - "8080:8080"
    
    depends_on:
      - mongo
    environment:
      #127.0.0.1
      #192.168.1.170
      API_ENDPOINT: https://spotify.home.lan # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://client.home.lan
      SPOTIFY_PUBLIC: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      CORS : https://client.home.lan
      MONGO_ENDPOINT	: mongodb://mongo:27017/your_spotify
    networks:
      - your_spotify
      - proxy

  
  # erreur pas d'avx sur mes xeon
  # :4.4.6
  #a ba si
  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/PERSO/yourspotify/db:/data/db
      - /mnt/PERSO/yourspotify/configdb:/data/configdb 
    networks:
      - your_spotify

  web:
    container_name: your_spotify_client
    image: yooooomi/your_spotify_client
    restart: always
    # ports:
    #   - "3000:3000"
    environment:
      API_ENDPOINT: https://spotify.home.lan
    networks:
      - your_spotify
      - proxy


networks:
  proxy:
    external: true
    name: proxy
  your_spotify:
