services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://192.168.1.170:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://192.168.1.170:3000
      SPOTIFY_PUBLIC: ${SPOTIFY_ID}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}

  
  # erreur pas d'avx sur mes xeon
  # :4.4.6
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://192.168.1.170:8080