services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - /mnt/PERSO/qbittorrent/main/config:/plugin
      - /mnt/PERSO/qbittorrent/main/files:/downloads #optional
    # ports:
    #   - 8081:8081
    network_mode: "service:protonvpn"
    depends_on:
      - protonvpn
    restart: unless-stopped
    
  protonvpn:
    image: docker.io/qmcgaw/gluetun:latest
    container_name: protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Etc/UTC
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1'
    volumes:
      - ./vpn:/gluetun
    ports:
      - 8081:8081
      - 9117:9117
    restart: unless-stopped
    
  
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /mnt/PERSO/qbittorrent/jackett/config:/config
      - /mnt/PERSO/qbittorrent/jackett/blackhole:/downloads
    network_mode: "service:protonvpn"
    # ports:
    #   - 9117:9117
    restart: unless-stopped

volumes:
  torrentconfig:
    external: true
  torrentfiles:
    external: true
