
networks:
  proxy:
    external: true   # le réseau 'proxy' existe déjà (sinon: docker network create proxy)

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    networks: [proxy]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
