services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    networks: [proxy]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/PERSO/caddy/config:/etc/caddy/:ro

      - /mnt/PERSO/caddy/cert:/config

networks:
  proxy:
    external: true # le réseau 'proxy' existe déjà (sinon: docker network create proxy)

