services:
  endurain:
    container_name: endurain-app
    image: ghcr.io/joaovitoriasilva/endurain:latest
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
      - GEOCODES_MAPS_API=${GEOCODES_MAPS_API}
      - TZ=${TZ}
      - ENDURAIN_HOST=${ENDURAIN_HOST}
      - BEHIND_PROXY=${BEHIND_PROXY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      #  - <local_path>/endurain/backend/app:/app/backend # Configure volume if you want to edit the code locally by cloning the repo
      - /mnt/PERSO/endurain/data:/app/backend/data # necessary for activity files, user images and server images persistence on container image updates
      - /mnt/PERSO/endurain/logs:/app/backend/logs # log files for the backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

    # postgres logic
  postgres:
    image: docker.io/postgres:17.5
    container_name: endurain-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=${PGDATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endurain"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

